[project]
name = "jmake"
description = "C++ build system"
readme = "README.md"
version = "0.0.1"
requires-python = ">=3.7"
license = { file = "LICENSE" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
